# This is a basic workflow to help you get started with Actions

name: CI for TestNG

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # No need to install Maven as they already installed on the machine
      
      - name: Run TestNG using maven
        run: |
              cd Automatic_Testing
              mvn clean test -Dsurefire.suiteXmlFiles=TestNG.xml

      - uses: actions/upload-artifact@v4
        with:
          name: TestNg Reports
          path: ./test-output
